# test_latest_diff.ps1 — Test the /latest and /changes diff endpoints
# Usage: .\scripts\test_latest_diff.ps1
# Reads REST_API_URL and REST_API_TOKEN from .env (auto-generated by app)
#
# Tests:
#   1. GET /latest?scope=task       (full task diff via composite endpoint)
#   2. GET /latest?scope=subtask    (latest subtask diff via composite endpoint)
#   3. GET /changes/workspaces      (discover workspaces)
#   4. GET /changes/tasks           (list tasks for workspace)
#   5. GET /changes/tasks/:id/steps (list steps)
#   6. GET /changes/tasks/:id/diff  (full task diff via changes endpoint)
#   7. GET /changes/tasks/:id/subtasks/:idx/diff  (subtask diff)
#   8. Raw git diff comparison      (verify git CLI works directly)

$ErrorActionPreference = "Stop"

# ============ Load .env ============
$envFile = Join-Path $PSScriptRoot "..\.env"
if (Test-Path $envFile) {
    Get-Content $envFile | ForEach-Object {
        if ($_ -match '^([^#=]+)=(.*)$') {
            [System.Environment]::SetEnvironmentVariable($matches[1].Trim(), $matches[2].Trim())
        }
    }
} else {
    Write-Host "ERROR: .env file not found at $envFile" -ForegroundColor Red
    Write-Host "Make sure the app is running first." -ForegroundColor Yellow
    exit 1
}

$baseUrl = $env:REST_API_URL
$token   = $env:REST_API_TOKEN

if (-not $baseUrl -or -not $token) {
    Write-Host "ERROR: REST_API_URL or REST_API_TOKEN not set in .env" -ForegroundColor Red
    exit 1
}

$headers = @{
    "Authorization" = "Bearer $token"
    "Content-Type"  = "application/json"
}

function Safe-Request {
    param([string]$Url, [string]$Label)
    try {
        $start = Get-Date
        $resp  = Invoke-RestMethod -Uri $Url -Headers $headers -Method Get -ErrorAction Stop
        $ms    = [math]::Round(((Get-Date) - $start).TotalMilliseconds)
        return @{ ok = $true; data = $resp; ms = $ms }
    } catch {
        $code = 0
        $body = ""
        if ($_.Exception.Response) {
            $code = [int]$_.Exception.Response.StatusCode
            try {
                $reader = New-Object System.IO.StreamReader($_.Exception.Response.GetResponseStream())
                $body   = $reader.ReadToEnd(); $reader.Close()
            } catch {}
        }
        return @{ ok = $false; error = $_.Exception.Message; code = $code; body = $body }
    }
}

function Show-DiffSummary {
    param($diff, [string]$Label)
    if (-not $diff) {
        Write-Host "    $Label diff: NULL" -ForegroundColor Red
        return
    }
    $fileCount = 0
    if ($diff.files) { $fileCount = $diff.files.Count }
    $patchLen  = 0
    if ($diff.patch) { $patchLen = $diff.patch.Length }
    $patchKB   = [math]::Round($patchLen / 1024, 1)

    $color = if ($fileCount -gt 0 -and $patchLen -gt 0) { "Green" } else { "Red" }
    Write-Host "    $Label" -ForegroundColor Cyan -NoNewline
    Write-Host ": $($diff.fromRef.Substring(0, [Math]::Min(8, $diff.fromRef.Length))) -> $($diff.toRef.Substring(0, [Math]::Min(8, $diff.toRef.Length)))" -ForegroundColor Gray -NoNewline
    Write-Host " | $fileCount files | ${patchKB}KB patch" -ForegroundColor $color

    if ($fileCount -eq 0 -and $patchLen -eq 0) {
        Write-Host "    *** EMPTY DIFF — this is the bug! ***" -ForegroundColor Red
    }

    if ($fileCount -gt 0) {
        $diff.files | Select-Object -First 5 | ForEach-Object {
            Write-Host "      $($_.status.PadRight(10)) $($_.path)  +$($_.linesAdded) -$($_.linesRemoved)" -ForegroundColor White
        }
        if ($fileCount -gt 5) {
            Write-Host "      ... and $($fileCount - 5) more" -ForegroundColor Gray
        }
    }
}

Write-Host "============================================" -ForegroundColor Cyan
Write-Host "  Latest & Diff Endpoint Test Suite" -ForegroundColor Cyan
Write-Host "============================================" -ForegroundColor Cyan
Write-Host "Base URL: $baseUrl" -ForegroundColor Gray
Write-Host ""

# ============ Test 1: GET /latest?scope=task ============
Write-Host "--- Test 1: GET /latest?scope=task ---" -ForegroundColor Yellow
$r = Safe-Request "$baseUrl/latest?scope=task" "latest-task"
if ($r.ok) {
    $d = $r.data
    Write-Host "  OK (${($r.ms)}ms)" -ForegroundColor Green
    Write-Host "    Task ID     : $($d.taskId)" -ForegroundColor White
    Write-Host "    Scope       : $($d.scope)" -ForegroundColor White
    Write-Host "    Subtask idx : $($d.subtaskIndex)" -ForegroundColor White
    Write-Host "    Total subs  : $($d.totalSubtasks)" -ForegroundColor White
    Write-Host "    Workspace   : $($d.workspaceId)" -ForegroundColor White
    Write-Host "    noDiffReason: $($d.noDiffReason)" -ForegroundColor $(if ($d.noDiffReason) { "Red" } else { "Gray" })
    Write-Host "    Messages    : $($d.messageCount)  Tools: $($d.toolCallCount)" -ForegroundColor White
    Show-DiffSummary $d.diff "Full Task Diff"

    # Save for later tests
    $latestTaskId    = $d.taskId
    $latestWorkspace = $d.workspaceId
} else {
    Write-Host "  FAILED ($($r.code)): $($r.error)" -ForegroundColor Red
    if ($r.body) { Write-Host "    Body: $($r.body)" -ForegroundColor DarkRed }
}
Write-Host ""

# ============ Test 2: GET /latest?scope=subtask ============
Write-Host "--- Test 2: GET /latest?scope=subtask ---" -ForegroundColor Yellow
$r = Safe-Request "$baseUrl/latest?scope=subtask" "latest-subtask"
if ($r.ok) {
    $d = $r.data
    Write-Host "  OK (${($r.ms)}ms)" -ForegroundColor Green
    Write-Host "    Task ID     : $($d.taskId)" -ForegroundColor White
    Write-Host "    Scope       : $($d.scope)" -ForegroundColor White
    Write-Host "    Subtask idx : $($d.subtaskIndex)" -ForegroundColor White
    Write-Host "    isInitial   : $($d.isInitialTask)" -ForegroundColor White
    Write-Host "    noDiffReason: $($d.noDiffReason)" -ForegroundColor $(if ($d.noDiffReason) { "Red" } else { "Gray" })
    Show-DiffSummary $d.diff "Subtask Diff"
} else {
    Write-Host "  FAILED ($($r.code)): $($r.error)" -ForegroundColor Red
    if ($r.body) { Write-Host "    Body: $($r.body)" -ForegroundColor DarkRed }
}
Write-Host ""

# ============ Test 3: GET /changes/workspaces ============
Write-Host "--- Test 3: GET /changes/workspaces ---" -ForegroundColor Yellow
$r = Safe-Request "$baseUrl/changes/workspaces" "workspaces"
$workspaces = @()
if ($r.ok) {
    $workspaces = $r.data.workspaces
    Write-Host "  OK (${($r.ms)}ms) — $($workspaces.Count) workspace(s)" -ForegroundColor Green
    $workspaces | Select-Object -First 3 | ForEach-Object {
        Write-Host "    [$($_.id)] active=$($_.active) tasks=$($_.taskCount) git=$($_.gitDir)" -ForegroundColor White
    }
} else {
    Write-Host "  FAILED ($($r.code)): $($r.error)" -ForegroundColor Red
}
Write-Host ""

# Pick first workspace for remaining tests
$testWsId  = if ($latestWorkspace) { $latestWorkspace } elseif ($workspaces.Count -gt 0) { $workspaces[0].id } else { $null }
$testWsGit = $null
if ($testWsId -and $workspaces.Count -gt 0) {
    $ws = $workspaces | Where-Object { $_.id -eq $testWsId } | Select-Object -First 1
    if ($ws) { $testWsGit = $ws.gitDir }
}

if (-not $testWsId) {
    Write-Host "No workspace available — skipping remaining tests" -ForegroundColor Yellow
    exit 0
}

# ============ Test 4: GET /changes/tasks?workspace=... ============
Write-Host "--- Test 4: GET /changes/tasks?workspace=$testWsId ---" -ForegroundColor Yellow
$r = Safe-Request "$baseUrl/changes/tasks?workspace=$testWsId" "tasks"
$tasks = @()
if ($r.ok) {
    $tasks = $r.data.tasks
    Write-Host "  OK (${($r.ms)}ms) — $($tasks.Count) task(s)" -ForegroundColor Green
    $tasks | Select-Object -First 5 | ForEach-Object {
        Write-Host "    [$($_.taskId)] steps=$($_.steps) files=$($_.filesChanged) last=$($_.lastModified)" -ForegroundColor White
    }
} else {
    Write-Host "  FAILED ($($r.code)): $($r.error)" -ForegroundColor Red
}
Write-Host ""

# Pick a task for diff tests (prefer the known latest, or first task)
$testTaskId = if ($latestTaskId) { $latestTaskId } elseif ($tasks.Count -gt 0) { $tasks[0].taskId } else { $null }

if (-not $testTaskId) {
    Write-Host "No task available — skipping diff tests" -ForegroundColor Yellow
    exit 0
}

Write-Host "  Using task: $testTaskId  workspace: $testWsId" -ForegroundColor Cyan
Write-Host ""

# ============ Test 5: GET /changes/tasks/:id/steps ============
Write-Host "--- Test 5: GET /changes/tasks/$testTaskId/steps ---" -ForegroundColor Yellow
$r = Safe-Request "$baseUrl/changes/tasks/$testTaskId/steps?workspace=$testWsId" "steps"
$steps = @()
if ($r.ok) {
    $steps = $r.data.steps
    Write-Host "  OK (${($r.ms)}ms) — $($steps.Count) step(s)" -ForegroundColor Green
    if ($steps.Count -gt 0) {
        Write-Host "    First: [$($steps[0].index)] $($steps[0].hash.Substring(0,8)) files=$($steps[0].filesChanged) ts=$($steps[0].timestamp)" -ForegroundColor White
        $last = $steps[$steps.Count - 1]
        Write-Host "    Last:  [$($last.index)] $($last.hash.Substring(0,8)) files=$($last.filesChanged) ts=$($last.timestamp)" -ForegroundColor White
    }
} else {
    Write-Host "  FAILED ($($r.code)): $($r.error)" -ForegroundColor Red
}
Write-Host ""

# ============ Test 6: GET /changes/tasks/:id/diff (full task diff) ============
Write-Host "--- Test 6: GET /changes/tasks/$testTaskId/diff (full task diff) ---" -ForegroundColor Yellow
$r = Safe-Request "$baseUrl/changes/tasks/$testTaskId/diff?workspace=$testWsId" "task-diff"
if ($r.ok) {
    Write-Host "  OK (${($r.ms)}ms)" -ForegroundColor Green
    Show-DiffSummary $r.data "Task Diff (changes endpoint)"
} else {
    Write-Host "  FAILED ($($r.code)): $($r.error)" -ForegroundColor Red
    if ($r.body) { Write-Host "    Body: $($r.body)" -ForegroundColor DarkRed }
}
Write-Host ""

# ============ Test 7: Subtask diffs ============
Write-Host "--- Test 7: Subtask diffs for task $testTaskId ---" -ForegroundColor Yellow

# First get subtask info from /history/tasks/:id/subtasks
$subtaskUrl = "$baseUrl/history/tasks/$testTaskId/subtasks"
$sr = Safe-Request $subtaskUrl "subtasks-list"
if ($sr.ok -and $sr.data.subtasks) {
    $subtaskCount = $sr.data.totalSubtasks
    Write-Host "  Found $subtaskCount subtask(s)" -ForegroundColor Green

    for ($i = 0; $i -lt $subtaskCount; $i++) {
        $sub = $sr.data.subtasks[$i]
        $label = if ($i -eq 0) { "Initial Task" } else { "Feedback #$i" }
        Write-Host ""
        Write-Host "  Subtask #$i ($label) — ts=$($sub.timestamp)" -ForegroundColor Cyan

        $dr = Safe-Request "$baseUrl/changes/tasks/$testTaskId/subtasks/$i/diff?workspace=$testWsId" "subtask-$i-diff"
        if ($dr.ok) {
            Write-Host "    OK (${($dr.ms)}ms)" -ForegroundColor Green
            Show-DiffSummary $dr.data "Subtask #$i Diff"
        } else {
            Write-Host "    FAILED ($($dr.code)): $($dr.error)" -ForegroundColor Red
            if ($dr.body) { Write-Host "      Body: $($dr.body)" -ForegroundColor DarkRed }
        }
    }
} else {
    Write-Host "  Could not fetch subtasks: $($sr.error)" -ForegroundColor Yellow
    # Try subtask 0 anyway
    $dr = Safe-Request "$baseUrl/changes/tasks/$testTaskId/subtasks/0/diff?workspace=$testWsId" "subtask-0-diff"
    if ($dr.ok) {
        Write-Host "  Subtask #0 direct:" -ForegroundColor Green
        Show-DiffSummary $dr.data "Subtask #0 Diff"
    } else {
        Write-Host "  Subtask #0 FAILED ($($dr.code)): $($dr.error)" -ForegroundColor Red
    }
}
Write-Host ""

# ============ Test 8: Raw git diff comparison ============
Write-Host "--- Test 8: Raw git diff (CLI comparison) ---" -ForegroundColor Yellow

if ($testWsGit -and (Test-Path $testWsGit)) {
    Write-Host "  Git dir: $testWsGit" -ForegroundColor Gray

    # Get commits for this task
    $gitLog = git --git-dir $testWsGit log --all --pretty=format:"%H|%s|%aI" 2>&1
    $taskCommits = @()
    foreach ($line in $gitLog -split "`n") {
        if ($line -match "^([a-f0-9]+)\|checkpoint-[^-]+-$testTaskId\|(.+)$") {
            $taskCommits += @{ hash = $matches[1]; ts = $matches[2] }
        }
    }

    # Reverse to chronological (oldest first)
    [array]::Reverse($taskCommits)

    Write-Host "  Task commits: $($taskCommits.Count)" -ForegroundColor White
    if ($taskCommits.Count -ge 1) {
        $first = $taskCommits[0].hash
        $last  = $taskCommits[$taskCommits.Count - 1].hash
        Write-Host "  First: $($first.Substring(0,8))  Last: $($last.Substring(0,8))" -ForegroundColor White

        # Raw git diff: first^ .. last
        Write-Host ""
        Write-Host "  Running: git diff --numstat $($first.Substring(0,8))^ $($last.Substring(0,8))" -ForegroundColor Gray
        $rawDiff = git --git-dir $testWsGit diff --numstat "$first^" $last 2>&1
        $rawLines = ($rawDiff -split "`n") | Where-Object { $_.Trim() -ne "" }
        $rawFileCount = $rawLines.Count

        $color = if ($rawFileCount -gt 0) { "Green" } else { "Red" }
        Write-Host "  Raw git diff: $rawFileCount files" -ForegroundColor $color
        $rawLines | Select-Object -First 10 | ForEach-Object {
            Write-Host "    $_" -ForegroundColor White
        }
        if ($rawFileCount -gt 10) {
            Write-Host "    ... and $($rawFileCount - 10) more" -ForegroundColor Gray
        }

        # Also test WITHOUT pathspec
        Write-Host ""
        Write-Host "  Running: git diff --numstat $($first.Substring(0,8))^ $($last.Substring(0,8)) -- ." -ForegroundColor Gray
        $rawDiff2 = git --git-dir $testWsGit diff --numstat "$first^" $last -- . 2>&1
        $rawLines2 = ($rawDiff2 -split "`n") | Where-Object { $_.Trim() -ne "" }
        Write-Host "  With '-- .' pathspec: $($rawLines2.Count) files" -ForegroundColor $(if ($rawLines2.Count -gt 0) { "Green" } else { "Red" })

        # Compare API vs git
        Write-Host ""
        if ($r.ok) {
            $apiFiles = $r.data.files.Count
            Write-Host "  COMPARISON: API=$apiFiles files  vs  git CLI=$rawFileCount files" -ForegroundColor $(if ($apiFiles -eq $rawFileCount) { "Green" } else { "Red" })
            if ($apiFiles -ne $rawFileCount) {
                Write-Host "  *** MISMATCH — API returns different file count than raw git! ***" -ForegroundColor Red
            }
        }
    } else {
        Write-Host "  No commits found for task $testTaskId in git log" -ForegroundColor Red
    }
} else {
    Write-Host "  SKIP: git dir not available ($testWsGit)" -ForegroundColor Yellow
}

Write-Host ""
Write-Host "============================================" -ForegroundColor Cyan
Write-Host "  Done" -ForegroundColor Cyan
Write-Host "============================================" -ForegroundColor Cyan
