# test_history.ps1 — Test the Conversation History API
# Usage: .\scripts\test_history.ps1
# Reads REST_API_URL and REST_API_TOKEN from .env (auto-generated by app)

$ErrorActionPreference = "Stop"

# Load .env file
$envFile = Join-Path $PSScriptRoot "..\.env"
if (Test-Path $envFile) {
    Get-Content $envFile | ForEach-Object {
        if ($_ -match '^([^#=]+)=(.*)$') {
            [System.Environment]::SetEnvironmentVariable($matches[1].Trim(), $matches[2].Trim())
        }
    }
} else {
    Write-Host "ERROR: .env file not found at $envFile" -ForegroundColor Red
    Write-Host "Make sure the app is running first." -ForegroundColor Yellow
    exit 1
}

$baseUrl = $env:REST_API_URL
$token = $env:REST_API_TOKEN

if (-not $baseUrl -or -not $token) {
    Write-Host "ERROR: REST_API_URL or REST_API_TOKEN not set in .env" -ForegroundColor Red
    exit 1
}

$headers = @{
    "Authorization" = "Bearer $token"
    "Content-Type" = "application/json"
}

Write-Host "=== Conversation History API Test ===" -ForegroundColor Cyan
Write-Host "Base URL: $baseUrl" -ForegroundColor Gray
Write-Host ""

# Test 1: GET /history/tasks (all tasks)
Write-Host "--- Test 1: GET /history/tasks ---" -ForegroundColor Yellow
$url = "$baseUrl/history/tasks"
Write-Host "  URL: $url" -ForegroundColor Gray

try {
    $start = Get-Date
    $response = Invoke-RestMethod -Uri $url -Headers $headers -Method Get
    $elapsed = ((Get-Date) - $start).TotalSeconds

    Write-Host "  Status: OK ({0:N1}s)" -f $elapsed -ForegroundColor Green
    Write-Host "  Total tasks: $($response.totalTasks)" -ForegroundColor White
    Write-Host "  Total messages: $($response.totalMessages)" -ForegroundColor White
    Write-Host "  Total tool calls: $($response.totalToolCalls)" -ForegroundColor White
    Write-Host "  Total API history: $([math]::Round($response.totalApiHistoryBytes / 1024 / 1024, 1)) MB" -ForegroundColor White
    Write-Host "  Tasks root: $($response.tasksRoot)" -ForegroundColor Gray
    
    Write-Host ""
    Write-Host "  Aggregate tool breakdown:" -ForegroundColor Cyan
    $response.aggregateToolBreakdown.PSObject.Properties | Sort-Object { $_.Value } -Descending | ForEach-Object {
        Write-Host "    $($_.Name): $($_.Value)" -ForegroundColor White
    }
    
    Write-Host ""
    Write-Host "  First 5 tasks (newest first):" -ForegroundColor Cyan
    $response.tasks | Select-Object -First 5 | ForEach-Object {
        $prompt = if ($_.taskPrompt) { $_.taskPrompt.Substring(0, [Math]::Min(80, $_.taskPrompt.Length)) } else { "(no prompt)" }
        Write-Host "    [$($_.taskId)] msgs=$($_.messageCount) tools=$($_.toolUseCount) model=$($_.modelId) | $prompt" -ForegroundColor White
    }
} catch {
    Write-Host "  FAILED: $($_.Exception.Message)" -ForegroundColor Red
}

Write-Host ""

# Test 2: GET /history/tasks?limit=3 (pagination)
Write-Host "--- Test 2: GET /history/tasks?limit=3 ---" -ForegroundColor Yellow
$url = "$baseUrl/history/tasks?limit=3"

try {
    $response = Invoke-RestMethod -Uri $url -Headers $headers -Method Get
    Write-Host "  Tasks returned: $($response.tasks.Count) (limit=3)" -ForegroundColor Green
    $response.tasks | ForEach-Object {
        Write-Host "    [$($_.taskId)] started=$($_.startedAt)" -ForegroundColor White
    }
} catch {
    Write-Host "  FAILED: $($_.Exception.Message)" -ForegroundColor Red
}

Write-Host ""

# Test 3: GET /history/tasks?model=claude (filter by model)
Write-Host "--- Test 3: GET /history/tasks?model=claude ---" -ForegroundColor Yellow
$url = "$baseUrl/history/tasks?model=claude"

try {
    $response = Invoke-RestMethod -Uri $url -Headers $headers -Method Get
    Write-Host "  Tasks matching 'claude': $($response.totalTasks)" -ForegroundColor Green
} catch {
    Write-Host "  FAILED: $($_.Exception.Message)" -ForegroundColor Red
}

Write-Host ""

# Test 4: No auth (should fail)
Write-Host "--- Test 4: GET /history/tasks (no auth — expect 401) ---" -ForegroundColor Yellow
$url = "$baseUrl/history/tasks"

try {
    $response = Invoke-WebRequest -Uri $url -Method Get -ErrorAction SilentlyContinue
    Write-Host "  UNEXPECTED: Got $($response.StatusCode)" -ForegroundColor Red
} catch {
    $statusCode = $_.Exception.Response.StatusCode.value__
    if ($statusCode -eq 401) {
        Write-Host "  PASS: Got 401 Unauthorized (expected)" -ForegroundColor Green
    } else {
        Write-Host "  Got status: $statusCode" -ForegroundColor Yellow
    }
}

Write-Host ""

# Test 5: GET /history/tasks/:taskId (task detail)
Write-Host "--- Test 5: GET /history/tasks/:taskId (task detail) ---" -ForegroundColor Yellow

# First, get a valid task ID from the task list
try {
    $listResponse = Invoke-RestMethod -Uri "$baseUrl/history/tasks?limit=1" -Headers $headers -Method Get
    if ($listResponse.tasks.Count -gt 0) {
        $taskId = $listResponse.tasks[0].taskId
        $url = "$baseUrl/history/tasks/$taskId"
        Write-Host "  URL: $url" -ForegroundColor Gray

        $start = Get-Date
        $response = Invoke-RestMethod -Uri $url -Headers $headers -Method Get
        $elapsed = ((Get-Date) - $start).TotalSeconds

        Write-Host "  Status: OK ({0:N1}s)" -f $elapsed -ForegroundColor Green
        Write-Host "  Task ID: $($response.taskId)" -ForegroundColor White
        Write-Host "  Started: $($response.startedAt)" -ForegroundColor White
        Write-Host "  Ended: $($response.endedAt)" -ForegroundColor White
        Write-Host "  Messages: $($response.messageCount)" -ForegroundColor White
        Write-Host "  Tool calls: $($response.toolUseCount)" -ForegroundColor White
        Write-Host "  Thinking blocks: $($response.thinkingCount)" -ForegroundColor White
        Write-Host "  Files in context: $($response.filesInContextCount)" -ForegroundColor White
        Write-Host "  Files edited: $($response.filesEditedCount)" -ForegroundColor White
        Write-Host "  Files read: $($response.filesReadCount)" -ForegroundColor White
        Write-Host "  Has focus chain: $($response.hasFocusChain)" -ForegroundColor White
        Write-Host "  API history size: $([math]::Round($response.apiHistorySizeBytes / 1024, 1)) KB" -ForegroundColor White

        Write-Host ""
        Write-Host "  Tool breakdown:" -ForegroundColor Cyan
        $response.toolBreakdown.PSObject.Properties | Sort-Object { $_.Value } -Descending | ForEach-Object {
            Write-Host "    $($_.Name): $($_.Value)" -ForegroundColor White
        }

        Write-Host ""
        Write-Host "  Model usage:" -ForegroundColor Cyan
        $response.modelUsage | ForEach-Object {
            Write-Host "    [$($_.mode)] $($_.modelId) via $($_.modelProviderId)" -ForegroundColor White
        }

        Write-Host ""
        Write-Host "  Environment:" -ForegroundColor Cyan
        $response.environment | Select-Object -First 1 | ForEach-Object {
            Write-Host "    OS: $($_.osName) $($_.osVersion)" -ForegroundColor White
            Write-Host "    Host: $($_.hostName) $($_.hostVersion)" -ForegroundColor White
            Write-Host "    Cline: $($_.clineVersion)" -ForegroundColor White
        }

        Write-Host ""
        Write-Host "  Messages (first 3):" -ForegroundColor Cyan
        $response.messages | Select-Object -First 3 | ForEach-Object {
            $blockTypes = ($_.content | ForEach-Object { $_.type }) -join ", "
            Write-Host "    [$($_.index)] role=$($_.role) blocks=[$blockTypes] ts=$($_.timestamp)" -ForegroundColor White
        }

        Write-Host ""
        Write-Host "  Tool calls (first 5):" -ForegroundColor Cyan
        $response.toolCalls | Select-Object -First 5 | ForEach-Object {
            $inputPreview = if ($_.inputSummary.Length -gt 60) { $_.inputSummary.Substring(0, 60) + "..." } else { $_.inputSummary }
            Write-Host "    [$($_.callIndex)] $($_.toolName) | $inputPreview" -ForegroundColor White
        }

        if ($response.hasFocusChain -and $response.focusChain) {
            Write-Host ""
            Write-Host "  Focus chain (first 200 chars):" -ForegroundColor Cyan
            $preview = if ($response.focusChain.Length -gt 200) { $response.focusChain.Substring(0, 200) + "..." } else { $response.focusChain }
            Write-Host "    $preview" -ForegroundColor White
        }
    } else {
        Write-Host "  SKIP: No tasks available to test detail endpoint" -ForegroundColor Yellow
    }
} catch {
    Write-Host "  FAILED: $($_.Exception.Message)" -ForegroundColor Red
}

Write-Host ""

# Test 6: GET /history/tasks/:taskId (invalid task ID — expect 404)
Write-Host "--- Test 6: GET /history/tasks/9999999999999 (nonexistent — expect 404) ---" -ForegroundColor Yellow
$url = "$baseUrl/history/tasks/9999999999999"

try {
    $response = Invoke-WebRequest -Uri $url -Headers $headers -Method Get -ErrorAction SilentlyContinue
    Write-Host "  UNEXPECTED: Got $($response.StatusCode)" -ForegroundColor Red
} catch {
    $statusCode = $_.Exception.Response.StatusCode.value__
    if ($statusCode -eq 404) {
        Write-Host "  PASS: Got 404 Not Found (expected)" -ForegroundColor Green
    } else {
        Write-Host "  Got status: $statusCode" -ForegroundColor Yellow
    }
}

Write-Host ""

# Test 7: GET /history/tasks/:taskId (bad format — expect 400)
Write-Host "--- Test 7: GET /history/tasks/not-a-number (bad format — expect 400) ---" -ForegroundColor Yellow
$url = "$baseUrl/history/tasks/not-a-number"

try {
    $response = Invoke-WebRequest -Uri $url -Headers $headers -Method Get -ErrorAction SilentlyContinue
    Write-Host "  UNEXPECTED: Got $($response.StatusCode)" -ForegroundColor Red
} catch {
    $statusCode = $_.Exception.Response.StatusCode.value__
    if ($statusCode -eq 400) {
        Write-Host "  PASS: Got 400 Bad Request (expected)" -ForegroundColor Green
    } else {
        Write-Host "  Got status: $statusCode" -ForegroundColor Yellow
    }
}

Write-Host ""

# Test 8: GET /history/tasks/:taskId/messages (paginated messages — default)
Write-Host "--- Test 8: GET /history/tasks/:taskId/messages (default page) ---" -ForegroundColor Yellow

try {
    $listResponse = Invoke-RestMethod -Uri "$baseUrl/history/tasks?limit=1" -Headers $headers -Method Get
    if ($listResponse.tasks.Count -gt 0) {
        $taskId = $listResponse.tasks[0].taskId
        $url = "$baseUrl/history/tasks/$taskId/messages"
        Write-Host "  URL: $url" -ForegroundColor Gray

        $start = Get-Date
        $response = Invoke-RestMethod -Uri $url -Headers $headers -Method Get
        $elapsed = ((Get-Date) - $start).TotalSeconds

        Write-Host "  Status: OK ({0:N1}s)" -f $elapsed -ForegroundColor Green
        Write-Host "  Task ID: $($response.taskId)" -ForegroundColor White
        Write-Host "  Total messages: $($response.totalMessages)" -ForegroundColor White
        Write-Host "  Filtered count: $($response.filteredCount)" -ForegroundColor White
        Write-Host "  Offset: $($response.offset)  Limit: $($response.limit)" -ForegroundColor White
        Write-Host "  Has more: $($response.hasMore)" -ForegroundColor White
        Write-Host "  Messages returned: $($response.messages.Count)" -ForegroundColor White

        Write-Host ""
        Write-Host "  Messages:" -ForegroundColor Cyan
        $response.messages | Select-Object -First 5 | ForEach-Object {
            $blockTypes = ($_.content | ForEach-Object { $_.type }) -join ", "
            Write-Host "    [$($_.index)] role=$($_.role) blocks=[$blockTypes] ts=$($_.timestamp)" -ForegroundColor White
        }
    } else {
        Write-Host "  SKIP: No tasks available" -ForegroundColor Yellow
    }
} catch {
    Write-Host "  FAILED: $($_.Exception.Message)" -ForegroundColor Red
}

Write-Host ""

# Test 9: GET /history/tasks/:taskId/messages?limit=5&offset=2 (pagination)
Write-Host "--- Test 9: GET /history/tasks/:taskId/messages?limit=5&offset=2 ---" -ForegroundColor Yellow

try {
    $listResponse = Invoke-RestMethod -Uri "$baseUrl/history/tasks?limit=1" -Headers $headers -Method Get
    if ($listResponse.tasks.Count -gt 0) {
        $taskId = $listResponse.tasks[0].taskId
        $url = "$baseUrl/history/tasks/$taskId/messages?limit=5&offset=2"
        Write-Host "  URL: $url" -ForegroundColor Gray

        $response = Invoke-RestMethod -Uri $url -Headers $headers -Method Get
        Write-Host "  Messages returned: $($response.messages.Count) (limit=5, offset=2)" -ForegroundColor Green
        Write-Host "  Total: $($response.totalMessages)  Filtered: $($response.filteredCount)  HasMore: $($response.hasMore)" -ForegroundColor White
        if ($response.messages.Count -gt 0) {
            Write-Host "  First msg index: $($response.messages[0].index)" -ForegroundColor White
        }
    } else {
        Write-Host "  SKIP: No tasks available" -ForegroundColor Yellow
    }
} catch {
    Write-Host "  FAILED: $($_.Exception.Message)" -ForegroundColor Red
}

Write-Host ""

# Test 10: GET /history/tasks/:taskId/messages?role=assistant (filter by role)
Write-Host "--- Test 10: GET /history/tasks/:taskId/messages?role=assistant ---" -ForegroundColor Yellow

try {
    $listResponse = Invoke-RestMethod -Uri "$baseUrl/history/tasks?limit=1" -Headers $headers -Method Get
    if ($listResponse.tasks.Count -gt 0) {
        $taskId = $listResponse.tasks[0].taskId
        $url = "$baseUrl/history/tasks/$taskId/messages?role=assistant&limit=3"
        Write-Host "  URL: $url" -ForegroundColor Gray

        $response = Invoke-RestMethod -Uri $url -Headers $headers -Method Get
        Write-Host "  Total messages: $($response.totalMessages)  Assistant only: $($response.filteredCount)" -ForegroundColor Green
        Write-Host "  Messages returned: $($response.messages.Count)" -ForegroundColor White
        $response.messages | ForEach-Object {
            $blockTypes = ($_.content | ForEach-Object { $_.type }) -join ", "
            Write-Host "    [$($_.index)] role=$($_.role) blocks=[$blockTypes]" -ForegroundColor White
        }
    } else {
        Write-Host "  SKIP: No tasks available" -ForegroundColor Yellow
    }
} catch {
    Write-Host "  FAILED: $($_.Exception.Message)" -ForegroundColor Red
}

Write-Host ""

# Test 11: GET /history/tasks/:taskId/messages?role=invalid (bad role — expect 400)
Write-Host "--- Test 11: GET /history/tasks/:taskId/messages?role=invalid (expect 400) ---" -ForegroundColor Yellow

try {
    $listResponse = Invoke-RestMethod -Uri "$baseUrl/history/tasks?limit=1" -Headers $headers -Method Get
    if ($listResponse.tasks.Count -gt 0) {
        $taskId = $listResponse.tasks[0].taskId
        $url = "$baseUrl/history/tasks/$taskId/messages?role=invalid"

        $response = Invoke-WebRequest -Uri $url -Headers $headers -Method Get -ErrorAction SilentlyContinue
        Write-Host "  UNEXPECTED: Got $($response.StatusCode)" -ForegroundColor Red
    } else {
        Write-Host "  SKIP: No tasks available" -ForegroundColor Yellow
    }
} catch {
    $statusCode = $_.Exception.Response.StatusCode.value__
    if ($statusCode -eq 400) {
        Write-Host "  PASS: Got 400 Bad Request (expected)" -ForegroundColor Green
    } else {
        Write-Host "  Got status: $statusCode" -ForegroundColor Yellow
    }
}

Write-Host ""

# Test 12: GET /history/tasks/:taskId/messages/0 (single message — first message, full content)
Write-Host "--- Test 12: GET /history/tasks/:taskId/messages/0 (single message, full content) ---" -ForegroundColor Yellow

try {
    $listResponse = Invoke-RestMethod -Uri "$baseUrl/history/tasks?limit=1" -Headers $headers -Method Get
    if ($listResponse.tasks.Count -gt 0) {
        $taskId = $listResponse.tasks[0].taskId
        $url = "$baseUrl/history/tasks/$taskId/messages/0"
        Write-Host "  URL: $url" -ForegroundColor Gray

        $start = Get-Date
        $response = Invoke-RestMethod -Uri $url -Headers $headers -Method Get
        $elapsed = ((Get-Date) - $start).TotalSeconds

        Write-Host "  Status: OK ({0:N1}s)" -f $elapsed -ForegroundColor Green
        Write-Host "  Task ID: $($response.taskId)" -ForegroundColor White
        Write-Host "  Index: $($response.index)" -ForegroundColor White
        Write-Host "  Total messages: $($response.totalMessages)" -ForegroundColor White
        Write-Host "  Role: $($response.role)" -ForegroundColor White
        Write-Host "  Timestamp: $($response.timestamp)" -ForegroundColor White
        Write-Host "  Content blocks: $($response.content.Count)" -ForegroundColor White

        $response.content | ForEach-Object {
            $len = if ($_.textLength) { "$($_.textLength) chars" } elseif ($_.toolInputLength) { "input=$($_.toolInputLength) chars" } elseif ($_.toolResultLength) { "result=$($_.toolResultLength) chars" } else { "" }
            Write-Host "    [$($_.type)] $len" -ForegroundColor White
            if ($_.toolName) { Write-Host "      tool: $($_.toolName)" -ForegroundColor Gray }
            if ($_.text -and $_.text.Length -gt 100) {
                Write-Host "      text (first 100): $($_.text.Substring(0, 100))..." -ForegroundColor Gray
            } elseif ($_.text) {
                Write-Host "      text: $($_.text)" -ForegroundColor Gray
            }
        }
    } else {
        Write-Host "  SKIP: No tasks available" -ForegroundColor Yellow
    }
} catch {
    Write-Host "  FAILED: $($_.Exception.Message)" -ForegroundColor Red
}

Write-Host ""

# Test 13: GET /history/tasks/:taskId/messages/1 (second message — usually assistant with thinking)
Write-Host "--- Test 13: GET /history/tasks/:taskId/messages/1 (second message) ---" -ForegroundColor Yellow

try {
    $listResponse = Invoke-RestMethod -Uri "$baseUrl/history/tasks?limit=1" -Headers $headers -Method Get
    if ($listResponse.tasks.Count -gt 0 -and $listResponse.tasks[0].messageCount -gt 1) {
        $taskId = $listResponse.tasks[0].taskId
        $url = "$baseUrl/history/tasks/$taskId/messages/1"
        Write-Host "  URL: $url" -ForegroundColor Gray

        $response = Invoke-RestMethod -Uri $url -Headers $headers -Method Get
        Write-Host "  Role: $($response.role)  Blocks: $($response.content.Count)" -ForegroundColor Green
        $response.content | ForEach-Object {
            $len = if ($_.textLength) { "$($_.textLength) chars" } elseif ($_.toolInputLength) { "input=$($_.toolInputLength)" } elseif ($_.toolResultLength) { "result=$($_.toolResultLength)" } else { "" }
            Write-Host "    [$($_.type)] $len$(if ($_.toolName) { " tool=$($_.toolName)" } else { '' })" -ForegroundColor White
        }
    } else {
        Write-Host "  SKIP: No tasks or single-message task" -ForegroundColor Yellow
    }
} catch {
    Write-Host "  FAILED: $($_.Exception.Message)" -ForegroundColor Red
}

Write-Host ""

# Test 14: GET /history/tasks/:taskId/messages/99999 (out of bounds — expect 404)
Write-Host "--- Test 14: GET /history/tasks/:taskId/messages/99999 (out of bounds — expect 404) ---" -ForegroundColor Yellow

try {
    $listResponse = Invoke-RestMethod -Uri "$baseUrl/history/tasks?limit=1" -Headers $headers -Method Get
    if ($listResponse.tasks.Count -gt 0) {
        $taskId = $listResponse.tasks[0].taskId
        $url = "$baseUrl/history/tasks/$taskId/messages/99999"

        $response = Invoke-WebRequest -Uri $url -Headers $headers -Method Get -ErrorAction SilentlyContinue
        Write-Host "  UNEXPECTED: Got $($response.StatusCode)" -ForegroundColor Red
    } else {
        Write-Host "  SKIP: No tasks available" -ForegroundColor Yellow
    }
} catch {
    $statusCode = $_.Exception.Response.StatusCode.value__
    if ($statusCode -eq 404) {
        Write-Host "  PASS: Got 404 Not Found (expected)" -ForegroundColor Green
    } else {
        Write-Host "  Got status: $statusCode" -ForegroundColor Yellow
    }
}

Write-Host ""

# Test 15: GET /history/tasks/:taskId/messages/abc (bad index — expect 400)
Write-Host "--- Test 15: GET /history/tasks/:taskId/messages/abc (bad index — expect 400) ---" -ForegroundColor Yellow

try {
    $listResponse = Invoke-RestMethod -Uri "$baseUrl/history/tasks?limit=1" -Headers $headers -Method Get
    if ($listResponse.tasks.Count -gt 0) {
        $taskId = $listResponse.tasks[0].taskId
        $url = "$baseUrl/history/tasks/$taskId/messages/abc"

        $response = Invoke-WebRequest -Uri $url -Headers $headers -Method Get -ErrorAction SilentlyContinue
        Write-Host "  UNEXPECTED: Got $($response.StatusCode)" -ForegroundColor Red
    } else {
        Write-Host "  SKIP: No tasks available" -ForegroundColor Yellow
    }
} catch {
    $statusCode = $_.Exception.Response.StatusCode.value__
    if ($statusCode -eq 400) {
        Write-Host "  PASS: Got 400 Bad Request (expected)" -ForegroundColor Green
    } else {
        Write-Host "  Got status: $statusCode" -ForegroundColor Yellow
    }
}

Write-Host ""
Write-Host "=== Done ===" -ForegroundColor Cyan
